version: 2
jobs:
  lint:
    working_directory: ~/emoncms
    docker:
    - image: lachlanevenson/k8s-helm
    steps:
    - checkout
    - run: helm lint .

workflows:
  version: 2
  lint:
    jobs:
    - lint
