version: 2.1

executors:
  helm:
    working_directory: ~/emoncms
    docker:
    - image: lachlanevenson/k8s-helm

jobs:
  lint:
    executor: helm
    steps:
    - checkout
    - run: helm init --client-only
    - run: helm lint .

  package:
    executor: helm
    steps:
    - checkout
    - run: helm init --client-only
    - run: helm package .

workflows:
  version: 2
  lint:
    jobs:
    - lint
    - package:
        requires: ["lint"]
