{{- if .Values.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: emoncmsdocker-emon-phpfiwa
spec:
  accessModes: ["ReadWriteOnce"]
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.phpfiwaSize }}
{{- end -}}
