apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - env:
        - name: MQTT_BASETOPIC
          value: emon
        - name: MQTT_ENABLED
          value: "false"
        - name: MQTT_HOST
          value: localhost
        - name: MQTT_PASSWORD
          value: YOUR_MQTT_PASSWORD
        - name: MQTT_USER
          value: YOUR_MQTT_USER
        - name: MYSQL_DATABASE
          value: {{ .Values.db.mysqlDatabase }}
        - name: MYSQL_HOST
          value: db
        - name: MYSQL_PASSWORD
          value: {{ .Values.db.mysqlPassword }}
        - name: MYSQL_PORT
          value: "3306"
        - name: MYSQL_RANDOM_ROOT_PASSWORD
          value: {{ .Values.db.mysqlRandomRootPassword | quote }}
        - name: MYSQL_USER
          value: {{ .Values.db.mysqlUser }}
        - name: PRODUCTION
          value: "true"
        - name: REDIS_ENABLED
          value: {{ .Values.db.redisEnabled | quote }}
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PREFIX
          value: '''emoncms'''
        image: openenergymonitor/emoncms:latest
        name: web
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/lib/phpfiwa
          name: emoncmsdocker-emon-phpfiwa
        - mountPath: /var/lib/phpfina
          name: emoncmsdocker-emon-phpfina
        - mountPath: /var/lib/phptimeseries
          name: emoncmsdocker-emon-phptimeseries
      restartPolicy: Always
      volumes:
      - name: emoncmsdocker-emon-phpfiwa
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: emoncmsdocker-emon-phpfiwa
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: emoncmsdocker-emon-phpfina
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: emoncmsdocker-emon-phpfina
        {{- else }}
        emptyDir: {}
        {{- end }}
      - name: emoncmsdocker-emon-phptimeseries
        {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: emoncmsdocker-emon-phptimeseries
        {{- else }}
        emptyDir: {}
        {{- end }}
